-- Baseline: reflete exatamente o schema já gerado por Hibernate ddl-auto=update
-- em produção/dev até este ponto. A partir daqui, ddl-auto=validate — toda
-- mudança de schema passa a exigir uma migration V{n}__*.sql nova.
--
-- stock_embeddings NÃO está aqui de propósito: é gerida pelo PgVectorEmbeddingStore
-- do LangChain4j (createTable=true), fora do escopo do Flyway/Hibernate.

CREATE TABLE users (
    id          UUID PRIMARY KEY,
    google_id   VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    picture_url VARCHAR(255),
    created_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_google_id UNIQUE (google_id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE portfolio_items (
    id            UUID PRIMARY KEY,
    user_id       UUID NOT NULL,
    ticker        VARCHAR(255) NOT NULL,
    quantity      DOUBLE PRECISION NOT NULL,
    average_price DOUBLE PRECISION NOT NULL,
    purchase_date DATE,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_portfolio_items_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_portfolio_items_user_ticker UNIQUE (user_id, ticker)
);

CREATE TABLE score_history (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker                    VARCHAR(255) NOT NULL,
    analysis_date             DATE NOT NULL,
    score_geral               DOUBLE PRECISION NOT NULL,
    fundamentos               DOUBLE PRECISION NOT NULL,
    valuation                 DOUBLE PRECISION NOT NULL,
    regime_momentum           DOUBLE PRECISION NOT NULL,
    sentimento_institucional  DOUBLE PRECISION NOT NULL,
    retorno_acionista         DOUBLE PRECISION NOT NULL,
    gestao_risco              DOUBLE PRECISION NOT NULL,
    model_used                VARCHAR(255),
    prompt_version            VARCHAR(255),
    created_at                TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_score_history_ticker_date ON score_history (ticker, analysis_date);

CREATE TABLE stock_alerts (
    id            UUID PRIMARY KEY,
    ticker        VARCHAR(255) NOT NULL,
    alert_date    DATE NOT NULL,
    score_before  DOUBLE PRECISION NOT NULL,
    score_after   DOUBLE PRECISION NOT NULL,
    direction     VARCHAR(4) NOT NULL,
    magnitude     DOUBLE PRECISION NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL
);
