-- Introduz Stock como entidade canônica, substituindo o ticker solto por FK em
-- portfolio_items, score_history e stock_alerts.
--
-- Motivo: as 3 tabelas guardavam ticker como string sem constraint entre si.
-- portfolio_items e stock_alerts guardavam sem sufixo (ex.: "PETR4"); score_history
-- guardava com o sufixo .SA do yfinance (ex.: "PETR4.SA") — mesmo ativo, dois
-- formatos, nunca detectado porque não havia FK unindo as tabelas. Forma canônica
-- adotada aqui: ticker B3 puro, maiúsculo, sem .SA (ver TickerNormalizer.canonical).

CREATE TABLE stock (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker     VARCHAR(10) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_stock_ticker UNIQUE (ticker)
);

-- Backfill: um Stock por ticker distinto normalizado, agregando as 3 tabelas.
INSERT INTO stock (ticker, created_at)
SELECT DISTINCT UPPER(REGEXP_REPLACE(ticker, '\.sa$', '', 'i')), NOW()
FROM (
    SELECT ticker FROM portfolio_items
    UNION
    SELECT ticker FROM score_history
    UNION
    SELECT ticker FROM stock_alerts
) all_tickers;

-- portfolio_items: FK stock_id substitui a coluna ticker
ALTER TABLE portfolio_items ADD COLUMN stock_id BIGINT;
UPDATE portfolio_items p
SET stock_id = s.id
FROM stock s
WHERE s.ticker = UPPER(REGEXP_REPLACE(p.ticker, '\.sa$', '', 'i'));
ALTER TABLE portfolio_items ALTER COLUMN stock_id SET NOT NULL;
ALTER TABLE portfolio_items ADD CONSTRAINT fk_portfolio_items_stock FOREIGN KEY (stock_id) REFERENCES stock (id);
ALTER TABLE portfolio_items DROP CONSTRAINT uk_portfolio_items_user_ticker;
ALTER TABLE portfolio_items ADD CONSTRAINT uk_portfolio_items_user_stock UNIQUE (user_id, stock_id);
ALTER TABLE portfolio_items DROP COLUMN ticker;

-- score_history: FK stock_id substitui a coluna ticker
ALTER TABLE score_history ADD COLUMN stock_id BIGINT;
UPDATE score_history sh
SET stock_id = s.id
FROM stock s
WHERE s.ticker = UPPER(REGEXP_REPLACE(sh.ticker, '\.sa$', '', 'i'));
ALTER TABLE score_history ALTER COLUMN stock_id SET NOT NULL;
ALTER TABLE score_history ADD CONSTRAINT fk_score_history_stock FOREIGN KEY (stock_id) REFERENCES stock (id);
DROP INDEX idx_score_history_ticker_date;
CREATE INDEX idx_score_history_stock_date ON score_history (stock_id, analysis_date);
ALTER TABLE score_history DROP COLUMN ticker;

-- stock_alerts: FK stock_id substitui a coluna ticker
ALTER TABLE stock_alerts ADD COLUMN stock_id BIGINT;
UPDATE stock_alerts sa
SET stock_id = s.id
FROM stock s
WHERE s.ticker = UPPER(REGEXP_REPLACE(sa.ticker, '\.sa$', '', 'i'));
ALTER TABLE stock_alerts ALTER COLUMN stock_id SET NOT NULL;
ALTER TABLE stock_alerts ADD CONSTRAINT fk_stock_alerts_stock FOREIGN KEY (stock_id) REFERENCES stock (id);
ALTER TABLE stock_alerts DROP COLUMN ticker;
