-- Auditoria completa por análise: prompt exato enviado ao LLM + resposta bruta +
-- raciocínio/explicações que o prompt já pede (schema "analise"/"explicacao" por
-- dimensão) mas que até agora eram descartados após o parsing.
--
-- Ligada a score_history por FK simples (sem @OneToOne mapeado em Java) — tabela
-- de escrita frequente/consulta rara, score_history continua enxuta pro caso de
-- uso quente (série histórica/gráfico).

CREATE TABLE analysis_audit (
    id                                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    score_history_id                     BIGINT NOT NULL,
    prompt_full                          TEXT NOT NULL,
    raw_response                         TEXT NOT NULL,
    reasoning                            TEXT,
    resumo                               TEXT,
    explicacao_fundamentos               TEXT,
    explicacao_valuation                 TEXT,
    explicacao_regime_momentum           TEXT,
    explicacao_sentimento_institucional  TEXT,
    explicacao_retorno_acionista         TEXT,
    explicacao_gestao_risco              TEXT,
    created_at                           TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_analysis_audit_score_history UNIQUE (score_history_id),
    CONSTRAINT fk_analysis_audit_score_history FOREIGN KEY (score_history_id) REFERENCES score_history (id)
);
